pipeline {
    agent any
     parameters {
        string(defaultValue: "", description: 'What environment?', name: 'Environment')
        // choices are newline separated
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'Maven  Installed'
        jdk 'Java Installed'
    }
    stages {
        stage ('Checkout'){
            steps 
            {
                git (
                    url: 'https://github.com/msuthar11/DevOps_Project.git',
                    credentialsId: 'e506ef21-f4b9-4276-9911-3ce0b31350f7'
                )
            }
            
            }
    }
}